export const pagesEn = {
  rooms: {
    hero: {
      eyebrow: "Accommodations",
      title: "Rooms & Cabins",
      body: "Four refined categories of mountain lodging—each designed for Glatt kosher living, Shabbat comfort, and the quiet luxury of Costa Rica's highlands.",
    },
    planCta: "Plan Your Stay",
    includesLabel: "Included",
    idealForLabel: "Ideal for",
    availabilityLabel: "Available upon request",
    rooms: [
      {
        id: "luxury-suite",
        badge: "Suite",
        name: "Luxury Suite",
        description: "An elegant suite with cedar accents, separate living space, and panoramic valley views—crafted for couples or small families who value privacy and refinement.",
        includes: ["King or twin bedding configuration", "Kosher refreshment station", "Private terrace", "Shabbat-friendly lighting"],
        idealFor: "Couples and executive retreats seeking understated luxury.",
        image: "/images/hotel-gallery/jungle-veranda-mountain-view.webp",
        imageAlt: "Wooden veranda overlooking lush jungle valleys and mountain horizons",
        imageObjectPosition: "center center",
      },
      {
        id: "family-suite",
        badge: "Family",
        name: "Family Suite",
        description: "Generous interconnecting spaces with room for children, quiet reading corners, and easy access to family programming across the estate.",
        includes: ["Multiple sleeping areas", "Family lounge", "Enhanced storage", "Child-safe terrace access"],
        idealFor: "Families with children who want comfort without compromising standards.",
        image: "/images/hotel-gallery/luxury-villa-garden-pathway.webp",
        imageAlt: "Stone pathway between luxury villas in a tropical mountain garden",
        imageObjectPosition: "center center",
      },
      {
        id: "mountain-villa",
        badge: "Villa",
        name: "Mountain View Villa",
        description: "A private villa framed by cloud forest and volcanic horizons—spacious, serene, and ideal for multi-generational gatherings.",
        includes: ["Expansive great room", "Outdoor dining terrace", "Kosher kitchenette", "Dedicated concierge line"],
        idealFor: "Groups and extended families celebrating milestones together.",
        image: "/images/hotel-gallery/tropical-resort-arrival-driveway.webp",
        imageAlt: "Tropical resort arrival driveway through lush palm gardens",
        imageObjectPosition: "center center",
      },
      {
        id: "private-retreat",
        badge: "Private Residence",
        name: "Private Retreat Residence",
        description: "The estate's most secluded residence—reserved for guests who desire complete privacy, bespoke service, and an unhurried mountain escape.",
        includes: ["Full private grounds", "Personalized meal scheduling", "Priority excursion planning", "Enhanced Shabbat setup"],
        idealFor: "Ultra-private stays, leadership retreats, and exclusive family weeks.",
        image: "/images/hotel-gallery/palm-canopy-entrance-driveway.webp",
        imageAlt: "Private palm-lined entrance driveway at a luxury mountain retreat",
        imageObjectPosition: "center 40%",
      },
    ],
    cta: {
      title: "Reserve your preferred category",
      body: "Our team will guide you toward the residence that best suits your party, standards, and season—without obligation.",
      button: "Plan Your Stay",
    },
  },
  kosherJewishLife: {
    hero: {
      eyebrow: "Kosher & Jewish Life",
      title: "Kosher & Jewish Life",
      body: "Kosher details confirmed during inquiry. Jewish life support available upon request, with Shabbat-friendly hospitality shaped around your stay.",
    },
    dining: {
      eyebrow: "Dining & Kashrut",
      title: "Kosher dining, thoughtfully prepared",
      body: "Chef-driven kosher cuisine featuring Costa Rican produce and premium ingredients. Menus and meal timing are shaped around your family's needs and the season of your stay.",
      checklist: [
        {
          title: "Glatt / Mehadrin Standards",
          body: "Kosher standards are confirmed during inquiry. Mehadrin preferences and elevated standards can be discussed in advance with our team.",
        },
        {
          title: "Luxury Dining Experience",
          body: "Refined presentation and seasonal menus—crafted for a calm, elevated table in the mountains.",
        },
        {
          title: "Shabbat & Holiday Meals",
          body: "Shabbat-friendly hospitality and seasonal holiday meals can be arranged upon request as part of your stay planning.",
        },
        {
          title: "Family Adaptations",
          body: "Flexible timing and thoughtful options for families who want comfort without compromising standards.",
        },
        {
          title: "Personal Requests in Advance",
          body: "Share dietary preferences and special requests before arrival so every meal feels seamless.",
        },
      ],
    },
    jewishLife: {
      eyebrow: "Shabbat & Jewish Life",
      title: "A Jewish rhythm, upon request",
      body: "Jewish life support available upon request—coordinated discreetly with your party so the mountains feel like home.",
      cards: [
        {
          title: "Shabbat",
          body: "Shabbat-friendly hospitality in a peaceful mountain setting—communal meals, calm atmosphere, and observance arranged upon request.",
        },
        {
          title: "Prayers",
          body: "Prayer arrangements and schedules are coordinated in advance with your party.",
        },
        {
          title: "Holidays",
          body: "Pesach, Sukkot, and seasonal observances can be discussed as part of your stay planning—combining tradition with the natural beauty of Costa Rica.",
        },
        {
          title: "Learning",
          body: "Jewish life support available upon request. Study and learning arrangements can be discussed in advance with your group.",
        },
        {
          title: "Jewish Atmosphere",
          body: "A retreat designed for guests who wish to live Jewish rhythm comfortably and discreetly—from dining to quiet spaces across the estate.",
        },
        {
          title: "Family Hospitality",
          body: "Share your family's needs before arrival. Our team coordinates the details so your stay feels calm, clear, and welcoming.",
        },
      ],
    },
    faqLink: "View frequently asked questions",
    cta: {
      title: "Discuss your kosher and Jewish life needs",
      body: "Tell us about dietary standards, Shabbat preferences, and any arrangements you would like coordinated in advance.",
      button: "Contact Us",
      whatsapp: "WhatsApp",
      whatsappPlaceholder: "WhatsApp — available upon request",
    },
  },
  costaRicaGuide: {
    hero: {
      eyebrow: "Costa Rica Guide",
      title: "Costa Rica Guide",
      body: "A practical introduction to the highlands, nature, and experiences around our mountain retreat—so you can arrive informed and travel with confidence.",
    },
    intro: {
      title: "Discover Costa Rica",
      body: "Beyond the coastline, Costa Rica's central highlands offer cloud forests, volcanic landscapes, and a quieter rhythm—ideal for families and travelers seeking nature with refinement.",
    },
    attractions: {
      eyebrow: "Attractions",
      title: "12 Recommended Attractions near Cartago",
      body: "Well-known natural and cultural sites in Cartago province—volcanoes, valleys, gardens, and colonial landmarks. Details and access can change; confirm arrangements with our team when planning your stay.",
      photoCredit: "Photos via Wikimedia Commons",
      mapLinkLabel: "View on Google Maps",
      cards: [
        {
          id: "irazu",
          title: "Irazú Volcano National Park",
          body: "Costa Rica's highest volcano, with crater viewpoints and highland scenery in Cartago province.",
        },
        {
          id: "turrialba",
          title: "Turrialba Volcano National Park",
          body: "Volcanic landscapes in eastern Cartago. Access conditions can change—confirm before visiting.",
        },
        {
          id: "orosiValley",
          title: "Orosi Valley",
          body: "A scenic highland valley of coffee farms, rivers, and mountain views southeast of Cartago.",
        },
        {
          id: "basilica",
          title: "Basílica de Nuestra Señora de los Ángeles",
          body: "Costa Rica's most important pilgrimage church, located in the city of Cartago.",
        },
        {
          id: "lankester",
          title: "Lankester Botanical Garden",
          body: "A University of Costa Rica garden near Paraíso, known for orchids and tropical plant collections.",
        },
        {
          id: "guayabo",
          title: "Guayabo National Monument",
          body: "Costa Rica's largest known pre-Columbian archaeological site, near Turrialba.",
        },
        {
          id: "ujarras",
          title: "Ujarrás Ruins",
          body: "Colonial church ruins set among gardens in the Orosi Valley area.",
        },
        {
          id: "lakeCachi",
          title: "Lake Cachí",
          body: "A reservoir with scenic viewpoints in the Orosi Valley region.",
        },
        {
          id: "orosiChurch",
          title: "Iglesia de Orosi",
          body: "A historic colonial church in the Orosi Valley, still in active use.",
        },
        {
          id: "lasRuinas",
          title: "Ruinas de Santiago Apóstol",
          body: "Landmark church ruins in central Cartago, a reminder of the city's colonial past.",
        },
        {
          id: "tapanti",
          title: "Tapantí National Park",
          body: "A rainforest park south of the Orosi Valley, known for dense forest, misty trails, and waterfall scenery.",
        },
        {
          id: "catie",
          title: "CATIE Botanical Garden, Turrialba",
          body: "A tropical research and education campus in Turrialba with botanical gardens open to visitors.",
        },
      ],
    },
    routes: {
      eyebrow: "Routes & Tours",
      title: "Routes & Guided Tours",
      body: "Mountain drives, valley viewpoints, and forest paths can be woven into a relaxed itinerary—with private guides available when you prefer a curated outing.",
      items: [
        {
          title: "Suggested Routes",
          body: "Mountain drives, valley viewpoints, and forest paths can be woven into a relaxed itinerary. Routes are planned around your pace, interests, and schedule.",
        },
        {
          title: "Guided Tours",
          body: "Private guides lead volcano visits, rainforest walks, and scenic outings. Timing and arrangements respect your kosher schedule and family needs.",
        },
        {
          title: "Experiences Through the Hotel",
          body: "Excursions, transfers, and special requests are coordinated by our concierge—balancing adventure, rest, and the standards that matter to your family.",
        },
      ],
    },
    nature: {
      eyebrow: "Nature",
      title: "Nature & Mountains",
      body: "Crisp highland air, misty forests, and panoramic horizons define the mountain experience—a contrast to the humid tropical coast.",
    },
    families: {
      eyebrow: "Families",
      title: "Family Experiences",
      body: "Gentle nature walks, supervised activities, and unhurried outings suitable for children, teens, and multi-generational groups.",
    },
    practical: {
      eyebrow: "Before You Arrive",
      title: "Useful Information",
      body: "A few practical notes to help you arrive prepared for highland weather, nature trails, and a calm start to your stay.",
      items: [
        {
          title: "Weather & Seasons",
          body: "Highland areas are generally mild and pleasant, with tropical rains possible throughout the year. Light layers and rain-ready footwear are recommended.",
        },
        {
          title: "Before You Arrive",
          body: "Valid passport, travel insurance, comfortable walking shoes, and modest attire for nature trails. Share dietary and scheduling preferences with our team in advance.",
        },
      ],
    },
    cta: {
      title: "Plan your Costa Rica stay",
      body: "Our team will help you shape a mountain itinerary that suits your family, season, and pace.",
      button: "Plan Your Stay",
    },
  },
  diningKashrut: {
    hero: {
      eyebrow: "Culinary Excellence",
      title: "Dining & Kashrut",
      body: "A full-service Glatt kosher kitchen operating under continuous on-site supervision—where tropical ingredients meet the discipline of mehadrin standards.",
    },
    sections: [
      {
        title: "Glatt / Mehadrin Standards",
        body: "Every ingredient, every preparation, every service is governed by strict Glatt kosher protocols. Mehadrin options are available for guests who require elevated standards.",
      },
      {
        title: "Full Kosher Kitchen",
        body: "Separate meat and dairy facilities, dedicated equipment, and a trained kitchen team operating under continuous on-site kosher supervision.",
      },
      {
        title: "Shabbat & Holidays",
        body: "Communal Shabbat meals in a refined mountain setting, with traditional menus, elegant presentation, and an atmosphere of calm observance.",
      },
      {
        title: "Luxury Fine Dining",
        body: "Chef-driven menus featuring Costa Rican produce, premium kosher proteins, and presentation worthy of a world-class retreat.",
      },
      {
        title: "Family Dining",
        body: "Flexible meal times, children's options, and private dining arrangements for families who prefer intimacy without compromising kashrut.",
      },
      {
        title: "Trust & Peace of Mind",
        body: "Kashrut is not merely a label here—it is the foundation of every meal. Our standards are communicated clearly, supervised diligently, and upheld with the discretion our guests expect.",
      },
    ],
    faqTitle: "Kashrut Questions",
    faq: [
      { q: "What level of kashrut do you maintain?", a: "We operate under strict Glatt kosher standards with mehadrin options available. Full details are provided during the booking process." },
      { q: "Is there on-site supervision?", a: "Yes. Kosher supervision is maintained on-site throughout kitchen operations, deliveries, and meal service." },
      { q: "Can you accommodate Chalav Yisrael and Pas Yisrael?", a: "Yes. These standards can be confirmed as part of your stay preferences." },
    ],
    cta: {
      title: "Discuss your dietary requirements",
      body: "Share your family's kashrut needs and we will ensure every meal reflects your standards.",
      button: "Plan Your Stay",
    },
  },
  jewishLife: {
    hero: {
      eyebrow: "Spiritual Intention",
      title: "Jewish Life",
      body: "A retreat where prayer, Shabbat, and Torah are woven into the rhythm of the mountains—not added as an afterthought.",
    },
    sections: [
      {
        title: "Daily Prayers",
        body: "Shacharit, Mincha, and Maariv in a dedicated prayer space, with a warm minyan atmosphere and essential siddurim and chumashim available.",
      },
      {
        title: "Shabbat Experience",
        body: "Candle lighting, tefillah, communal meals, and a peaceful atmosphere designed for true menucha in nature.",
      },
      {
        title: "Jewish Atmosphere",
        body: "From the dining room to the walking paths, the retreat is shaped for guests who live Jewish life fully and comfortably.",
      },
      {
        title: "Torah & Learning",
        body: "Shiurim, chavruta opportunities, and guest lectures on request—tailored to your group's level and interests.",
      },
      {
        title: "Prayer Space & Torah",
        body: "The estate is designed to accommodate daily tefillah and traditional Shabbat observance. Prayer arrangements and Torah reading details are coordinated in advance with each group.",
      },
      {
        title: "Holiday Experiences",
        body: "Pesach, Sukkot, and seasonal programs are crafted to combine observance with the natural beauty of Costa Rica.",
      },
      {
        title: "A Quiet Jewish Community",
        body: "Like-minded families and travelers gather here in an atmosphere of refinement and respect—where Jewish rhythm feels natural, unhurried, and deeply restorative.",
      },
    ],
    cta: {
      title: "Plan a spiritually meaningful stay",
      body: "Tell us about your minyan needs, Shabbat preferences, and learning interests.",
      button: "Plan Your Stay",
    },
  },
  experiences: {
    hero: {
      eyebrow: "Costa Rica",
      title: "Curated Experiences",
      body: "Private excursions and restorative moments—always arranged with your kosher schedule and family rhythm in mind.",
    },
    sections: [
      {
        title: "Nature & Mountains",
        body: "Cloud forests, volcanic vistas, and crisp highland air—the quieter, more soulful side of Costa Rica.",
      },
      {
        title: "Private Excursions",
        body: "Guided volcano visits, rainforest trails, and hidden waterfalls with kosher-packed meals and flexible timing.",
      },
      {
        title: "Family Adventures",
        body: "Nature walks, gentle hikes, and supervised activities designed for children and teens.",
      },
      {
        title: "Rest & Wellness",
        body: "Spa treatments, yoga decks, and quiet terraces for guests who seek restoration as much as adventure.",
      },
      {
        title: "Private Experiences",
        body: "Every itinerary is built around your party—private guides, flexible timing, and excursions arranged to honor both adventure and observance.",
      },
      {
        title: "Personal Concierge",
        body: "Every excursion, transfer, and special request is coordinated by a dedicated concierge who understands kosher travel.",
      },
    ],
    cta: {
      title: "Design your itinerary",
      body: "Our concierge will craft a week that balances adventure, rest, and observance.",
      button: "Plan Your Stay",
    },
  },
  planYourStay: {
    hero: {
      eyebrow: "Begin Your Journey",
      title: "Plan Your Stay",
      body: "Share your preferences and our team will respond with tailored guidance on rooms, kashrut, and availability.",
    },
    form: {
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      country: "Country of Residence",
      guests: "Number of Guests",
      preferredDates: "Preferred Travel Period",
      preferredDatesPlaceholder: "e.g. Summer season",
      roomPreference: "Preferred Room Category",
      requirements: "Kashrut / Shabbat / Family Needs",
      message: "Additional Message",
      submit: "Submit Inquiry",
      whatsapp: "Continue on WhatsApp",
      roomOptions: ["Luxury Suite", "Family Suite", "Mountain View Villa", "Private Retreat Residence", "Not sure yet"],
      requirementOptions: ["Glatt standard", "Mehadrin preferences", "Shabbat arrangements", "Family programming", "Multiple needs"],
      success: "Thank you. Your inquiry has been received. Our team will be in touch shortly.",
    },
  },
  faq: {
    hero: {
      eyebrow: "Practical Details",
      title: "Frequently Asked Questions",
      body: "Clear answers to help you plan a luxury kosher retreat in Costa Rica with confidence.",
    },
    items: [
      { category: "Kashrut", q: "What kashrut standards do you follow?", a: "We maintain strict Glatt kosher operations with on-site supervision. Mehadrin preferences can be accommodated when arranged in advance." },
      { category: "Shabbat", q: "How is Shabbat observed at the retreat?", a: "Shabbat is central to the experience—communal meals, tefillah, and a calm, respectful atmosphere throughout the estate." },
      { category: "Families", q: "Is the retreat suitable for families?", a: "Yes. Family suites, children's programming, and flexible dining make the retreat ideal for multi-generational travel." },
      { category: "Children", q: "Are there activities for children?", a: "Supervised nature activities, family-friendly excursions, and dedicated spaces for children are available seasonally." },
      { category: "Travel", q: "How do I reach the retreat?", a: "The estate is located in the Cartago highlands. Private transfers from San José can be arranged through our concierge." },
      { category: "Rooms", q: "How many room categories are available?", a: "Four categories: Luxury Suite, Family Suite, Mountain View Villa, and Private Retreat Residence. Our team will help you choose." },
      { category: "Dining", q: "Are all meals included?", a: "Meal packages vary by season and booking type. Full details are provided during the inquiry process." },
      { category: "Booking", q: "How do I reserve?", a: "Submit an inquiry through our Plan Your Stay form or contact us directly. A dedicated advisor will guide you through the process." },
      { category: "Languages", q: "Which languages are supported?", a: "Our team communicates in English and Hebrew. Additional language support may be available on request." },
      { category: "Privacy", q: "How is guest privacy handled?", a: "We treat all personal information with discretion. Inquiry details are used solely to coordinate your stay." },
    ],
    cta: {
      title: "Still have questions?",
      body: "Our concierge team is ready to assist with any detail about your stay.",
      button: "Contact Us",
    },
  },
  contact: {
    hero: {
      eyebrow: "Reach Us",
      title: "Contact",
      body: "We welcome your questions about availability, kashrut, group arrangements, and bespoke mountain retreats.",
    },
    details: {
      phone: "Available upon request",
      email: "Available upon request",
      location: "Cartago Highlands, Costa Rica",
      hours: "Sunday – Thursday, 9:00 – 18:00 (CST)",
      phoneLabel: "Phone",
      emailLabel: "Email",
      locationLabel: "Location",
      whatsappPlaceholder: "WhatsApp — available upon request",
    },
    form: {
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      country: "Country",
      guests: "Guests",
      preferredDates: "Dates",
      roomPreference: "Room",
      requirements: "Requirements",
      message: "How may we assist you?",
      submit: "Send Message",
      whatsapp: "WhatsApp",
      roomOptions: ["General inquiry"],
      requirementOptions: ["General inquiry"],
      success: "Thank you for reaching out. We will respond shortly.",
    },
    cta: {
      title: "Prefer to speak directly?",
      body: "Connect with our concierge team for immediate assistance.",
      button: "Plan Your Stay",
    },
  },
  pesach: {
    hero: {
      eyebrow: "Pesach Retreat",
      title: "Pesach in Costa Rica",
      body: "A luxury Pesach holiday combining kashrut, tradition, family activities and Costa Rica experiences.",
      cta: "Inquire About Pesach",
    },
    highlights: {
      eyebrow: "A Pesach Experience Like No Other",
      title: "Luxury. Tradition. Freedom.",
      body: "A festive mountain Pesach shaped around refined hospitality, Jewish life and experiences for the whole family.",
      cta: "View Full Program",
      values: [
        {
          title: "Glatt / Mehadrin Dining",
          body: "Chef-driven kosher dining for Pesach—refined presentation and menus confirmed during inquiry.",
        },
        {
          title: "Prayer & Jewish Life",
          body: "Prayer support and Jewish life arrangements thoughtfully shaped around your holiday stay.",
        },
        {
          title: "Kids & Teen Programs",
          body: "Programs for children and teens as part of the Pesach experience, subject to final confirmation.",
        },
        {
          title: "Costa Rica Excursions",
          body: "Guided nature and Costa Rica experiences planned for the whole family.",
        },
      ],
    },
    activities: {
      eyebrow: "Holiday Highlights",
      title: "Activities for Everyone",
      items: [
        { id: "waterfall", title: "Waterfall Hikes" },
        { id: "zipline", title: "Zip-Line Adventures" },
        { id: "volcano", title: "Volcano Excursions" },
        { id: "spa", title: "Spa & Wellness" },
        { id: "beach", title: "Beach Trips / Nature Escape" },
        { id: "kids", title: "Kids Programs" },
        { id: "sports", title: "Sports & Recreation" },
        { id: "evening", title: "Evening Entertainment" },
      ],
    },
    dining: {
      eyebrow: "Gourmet Kosher Cuisine",
      titleLine1: "Exceptional Food.",
      titleLine2: "Memorable Moments.",
      body: "Chef-driven kosher dining for Pesach—refined presentation, warm atmosphere and menus confirmed during inquiry.",
      cta: "View Dining Experience",
      cards: [
        { id: "elegant", title: "Elegant Dining Experience" },
        { id: "chef", title: "Gourmet Chef-Prepared Meals" },
        { id: "desserts", title: "Passover Desserts" },
      ],
    },
    ribo: {
      eyebrow: "Featured Performance",
      artist: "Ishay Ribo",
      title: "Live Performance by Ishay Ribo",
      body: "A signature live evening within our Pesach adult entertainment program. Performance details are confirmed during inquiry.",
      imageAlt: "Ishay Ribo performing live on stage before a large audience",
      note: "Program subject to final confirmation",
      cta: "Inquire About the Performance",
    },
    rooms: {
      eyebrow: "Rooms & Cabins",
      title: "Stay in refined mountain lodging",
      body: "Suites and residences designed for kosher living and holiday comfort. Availability confirmed during inquiry.",
      availability: "Available upon request",
      cta: "Plan Your Stay",
    },
    chooseStay: {
      eyebrow: "Choose Your Stay",
      title: "Select how you’d like to celebrate",
      body: "Choose a full Pesach stay or share custom dates. Official holiday dates are confirmed with you during inquiry—we do not invent them here.",
      fullLabel: "Full Pesach",
      fullHint: "The complete holiday stay—dates confirmed during inquiry.",
      customLabel: "Custom Dates",
      customHint: "Tell us your preferred check-in and check-out dates.",
      checkIn: "Check-in",
      checkOut: "Check-out",
    },
    form: {
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      country: "Country",
      adults: "Number of Adults",
      children: "Number of Children",
      stayType: "Stay Type",
      preferredDates: "Preferred Dates",
      roomPreference: "Preferred Room Category",
      specialNeeds: "Special Requirements",
      message: "Message",
      submit: "Submit Inquiry",
      contactUs: "Contact Us",
      whatsapp: "WhatsApp",
      whatsappPlaceholder: "WhatsApp — available upon request",
      roomOptions: ["Luxury Suite", "Family Suite", "Mountain View Villa", "Private Retreat Residence", "Not sure yet"],
      success: "Thank you. Your Pesach inquiry has been received. Our team will be in touch shortly.",
    },
    faqPreview: {
      eyebrow: "FAQ",
      title: "Pesach questions, answered calmly",
      link: "View all FAQ",
      items: [
        {
          q: "What kosher standards apply for Pesach?",
          a: "Glatt / Mehadrin preferences are discussed during inquiry. Details confirmed during inquiry.",
        },
        {
          q: "Are children’s programs included?",
          a: "Children’s programming is part of the Pesach experience when arranged. Program subject to final confirmation.",
        },
        {
          q: "How do I choose Full Pesach vs custom dates?",
          a: "Select Full Pesach for the complete holiday stay, or Custom Dates to share your preferred check-in and check-out. Official dates are confirmed during inquiry.",
        },
      ],
    },
    cta: {
      title: "Create unforgettable memories with your family in Costa Rica.",
      body: "",
      button: "Inquire Now",
      secondary: "Contact Us",
    },
    homeTeaser: {
      eyebrow: "Pesach Retreat",
      title: "A luxury kosher Pesach in the mountains",
      body: "Our seasonal centerpiece: Glatt / Mehadrin dining, prayer and synagogue support, children’s programs, guided Costa Rica excursions, and adult entertainment—details confirmed during inquiry.",
      cta: "Explore Pesach Retreat",
      imageAlt: "Festive kosher outdoor dining pavilion at a mountain retreat",
      highlights: [
        "Glatt / Mehadrin kosher meals",
        "Daily prayers and synagogue",
        "Children’s programs",
        "Guided Costa Rica excursions",
        "Adult entertainment and live performances",
      ],
    },
    confirmedNote: "Details confirmed during inquiry",
    programNote: "Program subject to final confirmation",
  },
  sukkot: {
    temporaryBanner: "Temporary program overview — details confirmed during inquiry.",
    hero: {
      eyebrow: "Seasonal Retreat",
      title: "Sukkot Retreat in Costa Rica",
      body: "A thoughtfully planned Sukkot retreat combining kosher holiday hospitality, family activities, prayer arrangements and Costa Rica experiences.",
    },
    overview: {
      eyebrow: "Overview",
      title: "Sukkot in the Costa Rica highlands",
      body: "A thoughtfully planned Sukkot retreat combining kosher holiday hospitality, family activities, prayer arrangements and Costa Rica experiences. Program details, schedules and availability will be confirmed during inquiry.",
    },
    meals: {
      eyebrow: "Kosher Dining",
      title: "Kosher holiday meals",
      body: "Festive kosher dining for Sukkot, shaped around your family’s preferences. Standards and menus are confirmed during inquiry.",
      points: [
        "Holiday hospitality with kosher care",
        "Details confirmed during inquiry",
        "Program subject to final confirmation",
      ],
    },
    sukkah: {
      eyebrow: "Holiday Atmosphere",
      title: "Sukkah and festive atmosphere",
      body: "A warm Sukkot atmosphere shaped for celebration and rest. Specific sukkah arrangements are confirmed during inquiry.",
      points: [
        "Festive holiday hospitality",
        "Arrangements confirmed during inquiry",
        "Program subject to final confirmation",
      ],
    },
    prayer: {
      eyebrow: "Prayer",
      title: "Prayer arrangements",
      body: "Jewish life support for Sukkot, including prayer arrangements available upon request. Schedules are confirmed during inquiry.",
      points: [
        "Prayer support available upon request",
        "Details confirmed during inquiry",
        "A calm, respectful holiday rhythm",
      ],
    },
    children: {
      eyebrow: "For Children",
      title: "Children’s programs",
      body: "Family-minded holiday programming for children. Exact offerings are subject to final confirmation.",
      points: [
        "Family-friendly holiday activities",
        "Details confirmed during inquiry",
        "Program subject to final confirmation",
      ],
    },
    excursions: {
      eyebrow: "Costa Rica",
      title: "Excursions and family activities",
      body: "Costa Rica experiences planned with families and holiday timing in mind. Specific itineraries are confirmed during inquiry.",
      points: [
        "Family-oriented highland experiences",
        "Itineraries shaped around your schedule",
        "Program subject to final confirmation",
      ],
    },
    adults: {
      eyebrow: "Adults",
      title: "Adult programming",
      body: "Evening and adult programming during the Sukkot retreat. Specific offerings are confirmed during inquiry.",
      points: [
        "Adult hospitality programming",
        "Details confirmed during inquiry",
        "Program subject to final confirmation",
      ],
    },
    rooms: {
      eyebrow: "Stay",
      title: "Rooms & cabins",
      body: "Suites, family spaces, and private residences selected for your party size and holiday needs. Availability confirmed during inquiry.",
      points: [
        "Luxury and family-friendly categories",
        "Shabbat-friendly hospitality",
        "Availability confirmed during inquiry",
      ],
    },
    chooseStay: {
      eyebrow: "Choose Your Stay",
      title: "Select how you’d like to celebrate",
      body: "Choose a full Sukkot stay or share custom dates. Official holiday dates are confirmed during inquiry.",
      fullLabel: "Full Sukkot",
      fullHint: "The complete holiday stay—dates confirmed during inquiry.",
      customLabel: "Custom Dates",
      customHint: "Tell us your preferred check-in and check-out dates.",
      checkIn: "Check-in",
      checkOut: "Check-out",
    },
    form: {
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      country: "Country",
      adults: "Number of Adults",
      children: "Number of Children",
      stayType: "Stay Type",
      roomPreference: "Preferred Room Category",
      specialNeeds: "Special Requirements",
      message: "Message",
      submit: "Submit Inquiry",
      contactUs: "Contact Us",
      whatsapp: "WhatsApp",
      whatsappPlaceholder: "WhatsApp — available upon request",
      roomOptions: ["Luxury Suite", "Family Suite", "Mountain View Villa", "Private Retreat Residence", "Not sure yet"],
      success: "Thank you. Your Sukkot inquiry has been received. Our team will be in touch shortly.",
    },
    cta: {
      title: "Begin your Sukkot inquiry",
      body: "Share your preferences and our team will guide availability and holiday planning—without obligation.",
      button: "Submit Inquiry",
      secondary: "Contact Us",
    },
    programNote: "Program details, schedules and availability will be confirmed during inquiry.",
  },
  yearRound: {
    hero: {
      eyebrow: "Year-Round",
      title: "Kosher stays throughout the year",
      body: "A luxury Glatt kosher mountain retreat for couples, families, and groups—available beyond the holiday seasons, with hospitality shaped around your dates.",
    },
    overview: {
      eyebrow: "Overview",
      title: "A kosher vacation, any season",
      body: "Enjoy the Cartago highlands with kosher dining, Shabbat-friendly hospitality, and curated Costa Rica experiences. Details confirmed during inquiry.",
    },
    rooms: {
      eyebrow: "Accommodations",
      title: "Rooms & cabins",
      body: "From intimate suites to private residences—every space is designed for kosher living and mountain quiet.",
      points: [
        "Luxury Suite, Family Suite, villas, and private residences",
        "Availability confirmed during inquiry",
        "Shabbat-friendly hospitality",
      ],
    },
    dining: {
      eyebrow: "Dining & Kashrut",
      title: "Kosher dining",
      body: "Chef-driven kosher cuisine with standards confirmed during inquiry. Menus are shaped around your family’s needs and the season of your stay.",
      points: [
        "Glatt / Mehadrin preferences discussed in advance",
        "Details confirmed during inquiry",
        "Flexible meal planning for families and groups",
      ],
    },
    jewishLife: {
      eyebrow: "Jewish Life",
      title: "Jewish life & Shabbat",
      body: "Jewish life support available upon request, with Shabbat-friendly hospitality woven into the rhythm of your retreat.",
      points: [
        "Shabbat-friendly arrangements",
        "Prayer support available upon request",
        "Details confirmed during inquiry",
      ],
    },
    excursions: {
      eyebrow: "Experiences",
      title: "Excursions & attractions",
      body: "Volcanoes, cloud forests, waterfalls, and highland routes—planned with your schedule and kosher needs in mind.",
      points: [
        "Private guided options available upon request",
        "Itineraries shaped around your stay",
        "Program subject to final confirmation",
      ],
    },
    families: {
      eyebrow: "Families",
      title: "Family-friendly stays",
      body: "Spacious lodging and family-minded programming so parents can rest and children can enjoy the highlands.",
      points: [
        "Family suites and flexible spaces",
        "Activities arranged to suit your party",
        "Details confirmed during inquiry",
      ],
    },
    custom: {
      eyebrow: "Bespoke",
      title: "Tailored planning",
      body: "Tell us your dates, room preferences, and special needs—our concierge will shape a stay that fits.",
      points: [
        "Flexible arrival and departure",
        "Group and multi-generational options",
        "Personal guidance through inquiry",
      ],
    },
    chooseStay: {
      eyebrow: "Plan Your Dates",
      title: "Choose your preferred stay",
      body: "Share custom check-in and check-out dates. Availability is confirmed during inquiry.",
      customLabel: "Custom Dates",
      customHint: "Tell us your preferred check-in and check-out dates.",
      checkIn: "Check-in",
      checkOut: "Check-out",
    },
    form: {
      fullName: "Full Name",
      email: "Email",
      phone: "Phone",
      country: "Country",
      adults: "Number of Adults",
      children: "Number of Children",
      stayType: "Stay Type",
      roomPreference: "Preferred Room Category",
      specialNeeds: "Special Requirements",
      message: "Message",
      submit: "Submit Inquiry",
      contactUs: "Contact Us",
      whatsapp: "WhatsApp",
      whatsappPlaceholder: "WhatsApp — available upon request",
      roomOptions: ["Luxury Suite", "Family Suite", "Mountain View Villa", "Private Retreat Residence", "Not sure yet"],
      success: "Thank you. Your inquiry has been received. Our team will be in touch shortly.",
    },
    cta: {
      title: "Plan a year-round stay",
      body: "Share your preferences and our concierge will guide rooms, kashrut, and timing—without obligation.",
      button: "Submit Inquiry",
      secondary: "Contact Us",
    },
    programNote: "Details confirmed during inquiry",
  },
  holidays: {
    hero: {
      eyebrow: "Holidays & Stays",
      title: "Holidays & Stays",
      body: "Three clear pathways for celebrating and resting at Pura Shalom—Pesach, Sukkot, and year-round kosher stays in Costa Rica’s mountains.",
    },
    intro: {
      title: "Choose the stay that fits your season",
      body: "Explore our holiday retreats and flexible year-round hospitality. Program details and availability are confirmed during inquiry.",
    },
    pathways: {
      pesach: {
        eyebrow: "Featured Season",
        title: "Pesach Retreat",
        body: "A luxury Glatt kosher Pesach in the mountains—holiday dining, prayer support, family programs, excursions, and adult entertainment.",
        cta: "Explore Pesach",
        imageAlt: "Luxury Pesach table overlooking Costa Rica",
      },
      sukkot: {
        eyebrow: "Seasonal Retreat",
        title: "Sukkot Retreat",
        body: "A thoughtfully planned Sukkot stay with kosher holiday hospitality, family activities, prayer arrangements, and Costa Rica experiences.",
        cta: "Explore Sukkot",
        imageAlt: "Elegant Sukkot dining experience in Costa Rica",
      },
      yearRound: {
        eyebrow: "Anytime",
        title: "Year-Round Stays",
        body: "Kosher mountain hospitality beyond the holidays—rooms, dining, Shabbat-friendly stays, and curated highland experiences.",
        cta: "Explore Year-Round",
        imageAlt: "Luxury tropical retreat in the mountains of Costa Rica",
      },
    },
    cta: {
      title: "Not sure where to begin?",
      body: "Tell us your season and party size—our team will guide the right pathway.",
      button: "Contact Us",
    },
  },
  home: {
    intro: {
      title: "A luxury kosher retreat designed around your stay",
      body: "A private retreat in Costa Rica combining refined hospitality, Jewish life and thoughtfully planned experiences for families and groups.",
      bridge: "Discover our holiday retreats and year-round stays",
      values: [
        {
          title: "Kosher & Jewish Life",
          body: "Kosher dining, Shabbat, prayer and Jewish traditions are thoughtfully integrated into your stay, with final arrangements confirmed during inquiry.",
        },
        {
          title: "Luxury Mountain Hospitality",
          body: "A calm and refined stay surrounded by nature, with private-style hospitality, comfortable lodging and personal attention.",
        },
        {
          title: "Family Retreat Experience",
          body: "Programs for children and adults, guided experiences and a stay planned around the needs of your family or group.",
        },
      ],
    },
    trust: [
      { value: "Glatt", label: "Kosher Standards" },
      { value: "24/7", label: "Dedicated Concierge" },
      { value: "Private", label: "Mountain Estate" },
      { value: "Family", label: "Welcoming" },
    ],
    previews: {
      rooms: {
        eyebrow: "Accommodations",
        title: "Rooms & Residences",
        body: "From intimate suites to private villas—every space is designed for kosher living and mountain serenity.",
        link: "View Rooms",
        imageAlt: "Mountain suite terrace at a luxury kosher retreat",
      },
      dining: {
        eyebrow: "Dining & Kashrut",
        title: "Glatt Kosher Cuisine",
        body: "A full-service kitchen under permanent supervision, with Shabbat meals and chef-driven menus.",
        link: "Explore Dining",
        imageAlt: "Elegant Glatt kosher fine dining plate with mountain herbs",
      },
      jewishLife: {
        eyebrow: "Jewish Life",
        title: "Prayer, Shabbat & Torah",
        body: "Jewish life support available upon request, with Shabbat-friendly hospitality shaped around your stay.",
        link: "Discover Jewish Life",
        imageAlt: "Shabbat table setting at a kosher mountain retreat",
      },
      family: {
        eyebrow: "Family",
        title: "A Retreat for All Ages",
        body: "Family suites, children's activities, and programming that lets parents truly rest.",
        link: "Plan Your Stay",
        imageAlt: "Outdoor wellness deck for families at a mountain retreat",
      },
      experiences: {
        eyebrow: "Experiences",
        title: "Costa Rica, Curated",
        body: "Volcanic trails, cloud forests, and private excursions—always on your schedule.",
        link: "View Experiences",
        imageAlt: "Palm-lined driveway leading into Costa Rica highland estate",
      },
      faq: {
        eyebrow: "FAQ",
        title: "Questions Answered",
        body: "Kashrut, Shabbat, travel, families, and booking—clear guidance before you arrive.",
        link: "Read FAQ",
      },
    },
    faqPreview: [
      { q: "What kashrut standards do you maintain?", a: "Kosher standards confirmed during inquiry, with guidance tailored to your family's needs." },
      { q: "Is the retreat family-friendly?", a: "Yes—a family-friendly retreat experience with suites, programming, and flexible dining for all ages." },
      { q: "How do I begin planning?", a: "Submit an inquiry through our contact page and our team will guide you personally." },
    ],
    links: {
      learnMore: "Learn more",
      exploreRooms: "Explore rooms",
      viewKosherDining: "View kosher dining",
      discoverJewishLife: "Discover Jewish Life",
      planYourStay: "Plan your stay",
      viewExperiences: "View experiences",
      readFaq: "Read FAQ",
      contactUs: "Contact us",
    },
  },
} as const;
