import { pagesEn } from "./pages/en";
import { pagesHe } from "./pages/he";

export type Language = "en" | "he";

export type SiteContent = (typeof siteContent)[Language];

export const siteContent = {
  en: {
    nav: {
      logo: "Pura Shalom",
      home: "Home",
      rooms: "Rooms & Cabins",
      holidays: "Holidays & Stays",
      pesach: "Pesach Retreat",
      sukkot: "Sukkot Retreat",
      yearRound: "Year-Round Stays",
      kosherJewishLife: "Kosher & Jewish Life",
      costaRicaGuide: "Costa Rica Guide",
      faq: "FAQ",
      contact: "Contact",
      planYourStay: "Plan Your Stay",
      diningKashrut: "Dining & Kashrut",
      jewishLife: "Jewish Life",
      experiences: "Experiences",
      searchPlaceholder: "Search",
      phone: "",
      phoneAria: "Call Pura Shalom",
      contactLinkAria: "Contact us",
      menuOpenAria: "Open menu",
      menuCloseAria: "Close menu",
      /** @deprecated legacy tab navigation — preserved for LegacyTabApp */
      discover: "Discover",
      planner: "Personalize Retreat",
      inquiries: "My Inquiries",
      chat: "Luxury Concierge AI",
      cta: "Request Availability",
    },
    pages: pagesEn,
    hero: {
      eyebrow: "Cartago, Costa Rica",
      titleBefore: "A Luxury Kosher Retreat in the ",
      titleEmphasis: "Mountains",
      titleAfter: " of Costa Rica",
      ctaPrimary: "Plan Your Stay",
      ctaSecondary: "View Rooms",
      scroll: "Scroll",
    },
    promise: {
      eyebrow: "Unrivaled Hospitality",
      title: "Arrive. Everything is already handled.",
      body: "From thoughtful kosher planning to a calm mountain setting, we curate every detail so you can arrive with confidence and ease.",
      cards: [
        {
          title: "Kosher Dining",
          body: "Kosher standards confirmed during inquiry. Chef-driven menus shaped around your family's needs and the season of your stay.",
        },
        {
          title: "Jewish Life",
          body: "Jewish life support available upon request, with Shabbat-friendly hospitality woven into the rhythm of your retreat.",
        },
        {
          title: "Family Retreat",
          body: "A family-friendly retreat experience with spacious lodging, quiet spaces, and programming arranged to suit your party.",
        },
      ],
    },
    location: {
      eyebrow: "Cartago Highland Sanctuary",
      title: "A quieter side of Costa Rica.",
      body: "Away from the humid coastlines, the high mountains of Cartago offer a crisp, spring-like alpine climate. Here, the majestic Irazú Volcano looms over lush, misty cloud forests and emerald valleys—a landscape of profound serenity perfect for spiritual reflection and deep family connection.",
      pin: "Cartago, Costa Rica (alpine elevation)",
      imageAlt: "Lush Cartago cloud forest mountains at sunrise with tropical birds in flight",
    },
    scrollStory: {
      imageAlt: "Montage of luxury kosher moments in Costa Rica",
      imageEyebrow: "BESPOKE ESCAPE",
      imageTitle: "Our Curated Hospitality",
      stages: [
        {
          label: "STAGE 01",
          title: "Seamless Arrival",
          body: "A premium private transfer from San José International Airport directly up to our mountain retreat. Your private, English-speaking local driver awaits you with fresh towels and kosher refreshments.",
        },
        {
          label: "STAGE 02",
          title: "Uncompromised Sanctuary",
          body: "Step into private villas or cloud suites designed from inception with your spiritual life in mind, featuring custom layouts, dual sinks, kosher kitchenettes, and modern electronic Sabbath key override configurations.",
        },
        {
          label: "STAGE 03",
          title: "Master Chef Fine-Dining",
          body: "Savor three gourmet meals each day. Master culinary teams merge Costa Rican volcanic soil produce, exotic palm hearts, and premium kosher meats — with kashrut standards confirmed during inquiry.",
        },
        {
          label: "STAGE 04",
          title: "Immersive Shabbat Harmony",
          body: "Connect deeply on Shabbat. Enter a sacred, phone-free haven cradled by rolling mist, communal festive dining, Inspiring guest lectures, beautiful Tefillah, and traditional melodies.",
        },
        {
          label: "STAGE 05",
          title: "Curated Excursions",
          body: "Discover private volcanic climbs, custom zipline runs, or coastal catamaran sails. Your private tour itineraries respect both prayer schedules and kashrut limits with customized timing.",
        },
      ],
    },
    dining: {
      eyebrow: "Culinary Excellence",
      title: "Kosher dining, without compromise.",
      body: "Our culinary team crafts daily menus celebrating the rich bounty of Costa Rica. Kosher standards confirmed during inquiry, with chef-driven dining shaped around your family's needs and the season of your stay.",
      checklist: [
        {
          title: "Glatt / Mehadrin Standards",
          body: "Kosher standards confirmed during inquiry. Mehadrin preferences can be arranged when discussed in advance.",
        },
        {
          title: "Volcanic Farm-to-Table",
          body: "Locally picked organic greens, berries, herbs, and highland coffee sourced from neighboring estates.",
        },
      ],
      imageAlt: "Gourmet kosher dining with roasted vegetables and mountain valley views",
    },
    jewishLife: {
      eyebrow: "Spiritual Intention",
      title: "Built around the rhythm of Jewish life.",
      subtitle: "Jewish life support available upon request, with Shabbat-friendly hospitality throughout your stay.",
      cards: [
        {
          title: "Jewish Life Support",
          body: "Jewish life support available upon request — prayer arrangements, Shabbat hospitality, and thoughtful coordination for your group.",
        },
        {
          title: "Shabbat Experience",
          body: "Shabbat-friendly hospitality in a peaceful mountain setting — communal meals, calm atmosphere, and space for true menucha in nature.",
        },
        {
          title: "Torah & Learning",
          body: "Shiurim, chavruta opportunities, and guest lectures on request — tailored to your group's level and interests.",
        },
      ],
      imageAlt: "Shabbat table setting at a kosher mountain retreat",
    },
    family: {
      eyebrow: "For All Generations",
      title: "A real, peaceful vacation for parents, too.",
      heroBadge: "FAMILY RETREAT",
      heroTitle: "Family-Friendly Retreat Experience",
      heroBody: "Private hospitality for families and groups — spacious suites, supervised nature activities, and programming arranged so parents can truly rest.",
      heroImageAlt: "Children exploring butterflies on a tropical nature walk",
      miniCards: [
        { label: "01 / COMFORT", title: "Family Suites" },
        { label: "02 / NATURE", title: "Guided Activities" },
        { label: "03 / DINING", title: "Flexible Meals" },
        { label: "04 / DISCOVER", title: "Family Excursions" },
      ],
    },
    carousel: {
      eyebrow: "The Sanctuary Canvas",
      title: "Luxury at your fingertips.",
      items: [
        { label: "AQUATICS", title: "Infinity Cloud Pool", alt: "Infinity cloud pool at sunset" },
        { label: "RELAXATION", title: "Lava Stone Spa", alt: "Lava stone spa treatment room" },
        { label: "STARRY EVENINGS", title: "Starlight Lounge", alt: "Tropical resort pool surrounded by lush palm trees and jungle hillside" },
        { label: "WELLNESS", title: "Sunrise Yoga Deck", alt: "Mountain lodge overlooking lush green valleys and tropical hills" },
        { label: "ARRIVAL", title: "Palm-Lined Drive", alt: "A lush, palm-lined driveway leading through tropical grounds toward a thatched-roof villa" },
        { label: "VISTAS", title: "Misty Mountain Balcony", alt: "A scenic view of misty tropical mountains from a white-railed balcony" },
      ],
    },
    experiences: {
      eyebrow: "Alpine Adventures",
      title: "Adventure, curated for the observant.",
      subtitle: "Private tours where your kashrut and scheduling are always respected.",
      cards: [
        { badge: "Private Peak Tour", title: "Irazú Volcano Expedition", alt: "Irazu Volcano Crater" },
        { badge: "Secluded Hike", title: "Secret Waterfalls", alt: "Secret Waterfall" },
        { badge: "Thrills", title: "Jungle Canopy Tour", alt: "Jungle Canopy Zip line" },
        { badge: "Ocean Escape", title: "Private Sunset Sail", alt: "Sunset catamaran cruise" },
      ],
    },
    rooms: {
      eyebrow: "Luxury Chambers",
      title: "Comfort for couples and groups.",
      body: "Every sanctuary suite and villa is thoroughly designed with separate bedding capabilities, kosher kitchen amenities, and Sabbath-compliant systems.",
      cta: "Explore Rooms",
      fromPrice: "Available upon request",
      perNight: "",
      selectPlanner: "Plan Your Stay",
      items: {
        "panorama-villa": {
          name: "The Panorama Villa",
          category: "Villa Collection",
          description: "4-Bedroom architectural masterpiece with high-vaulted cedar ceilings, breathtaking volcano views, a private heated plunge pool, and a fully equipped kosher kitchenette with double sinks.",
          features: ["Private Heated Pool", "Fully Equipped Kosher Kitchen", "Panoramic Balcony", "On-site Butler", "Shabbat Lamp Configurations"],
        },
        "cloud-forest-suite": {
          name: "Cloud Forest Suite",
          category: "Suites",
          description: "An intimate, quiet retreat for couples featuring high-quality oak and linen textures, a private outdoor rain shower, and an expansive garden terrace directly overlooking the valley.",
          features: ["Private Garden Terrace", "Outdoor Rain Shower", "Separable Twin/King Bedding", "Premium Kosher Espresso Bar", "Luxury Linen Linings"],
        },
      },
    },
    programs: {
      eyebrow: "Bespoke Seasons",
      title: "A Calendar of Sanctuary.",
      subtitle: "Special seasonal packages throughout the Jewish year.",
      cards: [
        {
          title: "Passover",
          body: "The ultimate Seder under the equatorial stars. Fully inclusive premium Glatt Kosher for Pesach culinary programs, kids camps, and scholars.",
          cta: "Request Passover Rates",
        },
        {
          title: "Sukkot",
          body: "Dine in our majestic custom mountain Sukkah overlooking the emerald valleys. Beautiful Tefillot, lulav & etrog concierge, and intermediate activities.",
          cta: "Book Sukkot package",
        },
        {
          title: "Winter Retreats",
          body: "Enjoy crisp highland sun during the cold Northern winter. Specialized active weeks tailored for family camps and exciting zip expeditions.",
          cta: "Learn More",
        },
      ],
    },
    trust: {
      title: "The details matter. We plan for them.",
      stats: [
        { value: "100%", label: "Glatt Kosher Certification" },
        { value: "24/7", label: "Dedicated Concierge" },
        { value: "Private", label: "Bespoke Airport Transfers" },
        { value: "Secure", label: "Private Volcanic Estate" },
      ],
    },
    finalCta: {
      eyebrow: "Begin your journey",
      title: "Experience absolute luxury.",
      body: "Our hospitality team is ready to coordinate your customized mountain sanctuary—with kosher standards confirmed during inquiry.",
      cta: "Plan Your Stay",
    },
    footer: {
      brand: "Pura Shalom",
      description: "An ultra-luxury Glatt kosher retreat in the pristine mountains of Cartago, Costa Rica.",
      badges: ["Glatt Kosher 24/7", "Shabbat Observant"],
      newsletterLabel: "Bespoke Newsletter",
      emailPlaceholder: "Enter your email",
      subscribe: "Subscribe",
      exploreTitle: "Explore",
      exploreLinks: ["The Promise", "Location", "Kosher Dining", "Accommodations"],
      inquireTitle: "Inquire",
      inquireLinks: ["Personalize Package", "Bespoke Concierge AI"],
      location: "Cartago Estate, Costa Rica",
      copyright: "© 2026 Pura Shalom. All rights reserved. A premium Glatt kosher mountain retreat in Costa Rica.",
    },
    planner: {
      eyebrow: "Sanctuary Planner",
      title: "Personalize your luxury retreat.",
      subtitle: "Configure dates, kosher parameters, excursions, and family programs to generate a real-time price quotation and submit your inquiry to our boutique advisory desk.",
      steps: {
        guestDetails: "Guest Details",
        accommodation: "Select Accommodation",
        kashrut: "Kashrut & Jewish Life",
        excursions: "Excursions & Adventures",
        family: "Family Programs",
        special: "Special Requests & Dietary Preferences",
      },
      labels: {
        fullName: "FULL NAME",
        email: "EMAIL ADDRESS",
        phone: "PHONE NUMBER",
        season: "PREFERRED SEASON / MONTH",
        nights: "NUMBER OF NIGHTS",
        adults: "ADULT GUESTS (13+)",
        children: "CHILDREN (0-12)",
        supervision: "SUPERVISION STANDARDS",
        dailyServices: "DAILY SERVICES",
        shabbatDining: "COMMUNAL SHABBAT DINING",
        communalSeats: "Communal seat allocations:",
        rate: "RATE",
        perNight: "/ Night",
        perPerson: "/ Person",
        perDay: "/ Day",
        perNightChild: "PER NIGHT / CHILD",
        estimatedTotal: "ESTIMATED TOTAL",
        subjectReview: "Subject to advisor review",
        privateTour: "PRIVATE TOUR",
        communal: "COMMUNAL",
      },
      placeholders: {
        fullName: "E.g., Johnathan Goldstein",
        email: "goldstein@example.com",
        phone: "+1 (555) 300-4000",
        season: "December 2026 / Chanukah",
        specialRequests: "E.g., We are celebrating our silver anniversary. We require Cholav Yisrael strictly and would love assistance arranging a private torah study for our son on Monday morning...",
      },
      accommodationHint: "Choose the architectural space that best fits your group. Dual sinks, separate bedroom layouts, and Sabbath-compliant parameters are fully integrated.",
      kashrutHint: "Our culinary program is 100% strict Glatt Kosher, Pas Yisrael, and Chalav Yisrael. You may choose specialized kashrut parameters below.",
      minyanLabel: "Reserve seats in Synagogue",
      minyanHint: "Secure seat spacing in the Shul for Shacharit, Mincha, and Maariv services. Includes Siddurim & Chumashim availability.",
      shabbatHint: "Reserve a private table at our spectacular Shabbat communal feast with silver kiddush cups and warm braided challah.",
      excursionsHint: "Customize your escape with private nature treks or adrenaline zipline runs. Every excursion is timed around minyan constraints and kashrut limits.",
      familyHint: "Supervised luxury rainforest camps, teen lounges, and childcare services so you can unwind with total peace of mind.",
      specialHint: "Please let our boutique travel advisory desk know of any physical accessibility needs, custom kashrut supervisions, allergy requests, or specific milestone celebrations (anniversaries, bar mitzvahs, family reunions).",
      submit: "Submit Inquiry & Reserve Spot",
      estimateTitle: "Bespoke Estimate",
      nightsAdults: "nights ×",
      adultsWord: "adults",
      kidsWord: "kids",
      supervisionSurcharge: "Supervision Surcharge",
      curatedExcursions: "CURATED EXCURSIONS",
      familyProgramming: "FAMILY PROGRAMMING",
      inclusionsTitle: "Standard Inclusions:",
      inclusionsBody: "3 Gourmet Glatt Kosher meals daily, airport transfer, full Shul/Synagogue access, on-site leisure amenities (Infinity Pool, Yoga Deck, Catamaran exclusions if selected).",
      pledgeTitle: "Our Booking Pledge",
      pledgeBody: "Submitting this inquiry holds your priority spot in our retreat. A luxury concierge will contact you via email or phone within 24 hours to review your schedule, fine-tune special requests, and finalize the reservation.",
      adultsOption: "Adults",
      childrenOption: "Children",
      guestsOption: "Guests",
      validationAlert: "Please fill in your name, email, and phone number to request availability.",
      kashrutTiers: {
        "glatt-standard": {
          name: "Glatt Kosher (CRC / OU)",
          description: "Full Mashgiach Temidi, Pas Yisrael, Chalav Yisrael standard.",
        },
        "beit-yosef": {
          name: "Beit Yosef Standard",
          description: "Strict Sephardic Beit Yosef meat standards under high supervision.",
        },
        chassidish: {
          name: "Chassidishe Shechita / Super-Strict",
          description: "Highest Hassidishe kashrut standards, custom hashgacha verification.",
        },
      },
      activities: {
        volcano: {
          name: "Irazú Volcano Expedition",
          description: "Guided private tour exploring the breathtaking active crater, volcanic ash fields, and misty peak heights of Cartago, with custom packed Glatt Kosher lunch boxes.",
          category: "Adventure",
        },
        waterfalls: {
          name: "Secret Rainforest Waterfalls Hike",
          description: "Explore hidden lush cascades plunging into vibrant turquoise pools, accompanied by professional naturalists. Includes customized paths based on guest stamina.",
          category: "Nature",
        },
        canopy: {
          name: "Jungle Canopy Zipline Tour",
          description: "Fly securely above the cloud forest canopies. Exceptional safety measures and breathtaking birds-eye views of the emerald-colored valley below.",
          category: "Adrenaline",
        },
        "sunset-sail": {
          name: "Private Sunset Catamaran Cruise",
          description: "Settle onto clean teak decks of a private luxury yacht at sunset. Includes complete on-board Glatt Kosher hors d'oeuvres and wine pairing options.",
          category: "Leisure",
        },
      },
      familyServices: {
        "kids-camp": {
          name: "Rainforest Kid's Camp",
          description: "Guided butterfly hikes, botanical art, and tropical nature exploration.",
        },
        nanny: {
          name: "Private Nanny Service",
          description: "On-demand, professionally trained luxury childcare.",
        },
        "teen-lounge": {
          name: "Teen Lounge Access",
          description: "Billiards, arcade, gaming consoles, and guided teen hiking treks.",
        },
      },
    },
    chat: {
      eyebrow: "Real-time Assistance",
      title: "Concierge AI Desk",
      subtitle: "Inquire about strict kashrut details, on-site minyan schedules, customizable baby-sitting, private waterfall excursions, or volcanic weather.",
      conciergeName: "The Sanctuary Concierge",
      conciergeRole: "Elite Hospitality Consultant",
      poweredBy: "Powered by Gemini",
      loading: "The Sanctuary Concierge is preparing bespoke suggestions...",
      placeholder: "Ask anything about Kashrut, Shabbat, Rooms, Excursions, and Weather...",
      welcome: `Shalom and welcome. I am "The Sanctuary Concierge," your personal luxury hospitality advisor.

I am at your absolute service to coordinate your Glatt Kosher parameters, custom volcano excursions, and spiritual sanctuary requests here in the crisp, beautiful mountains of Cartago, Costa Rica.

How may I custom-tailor your luxury escape today? Feel free to ask about our rooms, dining certification, Shabbat schedules, or local day trips.`,
      errorFallback: "I apologize, I encountered a brief connection error with the sanctuary desk. Our Glatt Kosher retreat is fully open, and we would be delighted to assist you directly via our retreat inquiry form! Please submit your request there.",
      emptyResponse: "I am here to assist you. Please let me know how I can help.",
      suggestions: [
        "What are your strict Kashrut standards?",
        "Tell me about the Panorama Villa amenities.",
        "Describe the Shabbat atmosphere at Altura.",
        "What is the mountain weather like in Cartago?",
        "Are there custom tours to the Irazú Volcano?",
      ],
    },
    inquiries: {
      eyebrow: "Travel advisor Board",
      title: "My luxury escape inquiries.",
      subtitle: "Track the progress of your luxury requests, download pre-booking invoices, and monitor active volcanic getaway countdowns.",
      emptyTitle: "No Active Inquiries Found",
      emptyBody: "You have not configured or submitted any escape inquiries yet. Visit the retreat planner to customize your first bespoke package.",
      emptyCta: "Open Retreat Planner",
      submittedLabel: "SUBMITTED INQUIRIES",
      createNew: "+ Create New Plan",
      statusReview: "ADVISOR REVIEW IN PROGRESS",
      submittedOn: "Submitted on",
      countdownLabel: "ALTURA ESCAPE COUTNDOWN",
      countdownTitle: "Your Costa Rican mountain sanctuary awaits!",
      countdownBody: "A luxury kosher travel advisor will reach out to",
      countdownBodyOr: "or",
      countdownBodyEnd: "shortly to lock in pricing and select exact dates.",
      daysLabel: "DAYS TO DECOMPRESS",
      specsTitle: "RESERVATION SPECIFICATIONS",
      programmingTitle: "CURATED PROGRAMMING",
      noActivities: "No custom excursions selected yet. You can coordinate them with your advisor.",
      specialTitle: "Special Accommodations & requests",
      costTitle: "PROVISIONAL COST ESTIMATION",
      costSubtitle: "All-inclusive VIP Retreat Package",
      costNote: "Subject to local seasonal multipliers",
      glattIncluded: "Glatt certification included",
      primaryContact: "Primary Contact:",
      bespokeDates: "Bespoke Dates:",
      adultGuests: "Adult Guests:",
      kashrutSelection: "Kashrut Selection:",
      adultsSuffix: "Adults",
      deleteConfirm: "Are you sure you want to cancel this retreat inquiry?",
      printTitle: "Print Estimate Receipt",
      deleteTitle: "Cancel/Delete Inquiry",
      statusPending: "Pending",
    },
    heroImageAlt: "Mountain valley view at a luxury kosher retreat in Cartago, Costa Rica",
  },
  he: {
    nav: {
      logo: "Pura Shalom",
      home: "בית",
      rooms: "חדרים ובקתות",
      holidays: "חגים וחופשות",
      pesach: "נופש פסח",
      sukkot: "נופש סוכות",
      yearRound: "חופשות לאורך השנה",
      kosherJewishLife: "כשרות וחיי יהדות",
      costaRicaGuide: "מדריך קוסטה ריקה",
      faq: "שאלות נפוצות",
      contact: "יצירת קשר",
      planYourStay: "תכננו את החופשה",
      diningKashrut: "אוכל וכשרות",
      jewishLife: "חיים יהודיים",
      experiences: "חוויות",
      searchPlaceholder: "חיפוש",
      phone: "",
      phoneAria: "התקשרו ל-Pura Shalom",
      contactLinkAria: "צרו קשר",
      menuOpenAria: "פתחו תפריט",
      menuCloseAria: "סגרו תפריט",
      /** @deprecated legacy tab navigation — preserved for LegacyTabApp */
      discover: "גלו",
      planner: "התאמה אישית",
      inquiries: "הפניות שלי",
      chat: "קונסיירז' AI",
      cta: "בדקו זמינות",
    },
    pages: pagesHe,
    hero: {
      eyebrow: "קרטגו, קוסטה ריקה",
      titleBefore: "ריטריט כשר יוקרתי ",
      titleEmphasis: "בהרי",
      titleAfter: " קוסטה ריקה",
      ctaPrimary: "תכננו את השהייה",
      ctaSecondary: "לחדרים",
      scroll: "גלילה",
    },
    promise: {
      eyebrow: "אירוח ללא פשרות",
      title: "מגיעים. הכול כבר מוכן.",
      body: "מתכנון כשרות מוקפד ועד אווירה הררית שקטה — אנחנו דואגים לכל פרט, כדי שתגיעו בביטחון וברוגע.",
      cards: [
        {
          title: "אוכל כשר",
          body: "פרטי הכשרות יאושרו בשיחת התאמה. תפריטים בהובלת שף, מותאמים לצרכי המשפחה ולעונת השהייה.",
        },
        {
          title: "חיים יהודיים",
          body: "אפשרות לתיאום צרכים יהודיים מראש, עם אירוח מותאם שבת לאורך כל השהייה.",
        },
        {
          title: "ריטריט משפחתי",
          body: "חוויה משפחתית יוקרתית ושקטה — לינה מרווחת, פינות מנוחה ותכנון שמותאם לגודל הקבוצה.",
        },
      ],
    },
    location: {
      eyebrow: "מקדש ההרים בקרטגו",
      title: "צד שקט יותר של קוסטה ריקה.",
      body: "רחוק מקווי החוף הלחים, הרי קרטגו הגבוהים מציעים אקלים אלפיני נעים וקריר. כאן, הר הגעש איראסו המרהיב שורר מעל יערות עננים ירוקים ועמקים אזמרגד — נוף של שלווה עמוקה, מושלם להתבוננות רוחנית ולחיבור משפחתי.",
      pin: "קרטגו, קוסטה ריקה (גובה אלפיני)",
      imageAlt: "יער עננים ירוק בקרטגו בשעות הזריחה עם ציפורים טרופיות",
    },
    scrollStory: {
      imageAlt: "רגעים כשרים יוקרתיים בקוסטה ריקה",
      imageEyebrow: "חופשה מותאמת אישית",
      imageTitle: "האירוח המוקפד שלנו",
      stages: [
        {
          label: "שלב 01",
          title: "הגעה חלקה",
          body: " הסעה פרטית פרימיום משדה התעופה הבינלאומי של סן חוסה ישירות אל הריטריט בהרים. נהג מקומי פרטי דובר אנגלית ממתין לכם עם מגבות רעננות וכיבוד כשר.",
        },
        {
          label: "שלב 02",
          title: "מקדש ללא פשרות",
          body: "היכנסו לווילות פרטיות או לסוויטות בעננים, שתוכננו מהיסוד עם החיים הרוחניים שלכם בראש — פריסות מותאמות, כיורים כפולים, מטבחונים כשרים ומערכות שבת אלקטרוניות.",
        },
        {
          label: "שלב 03",
          title: "ארוחות כשרות ברמה עולמית",
          body: "טעמו שלוש ארוחות gourmet ביום. צוותי המטבח המובילים משלבים תוצרת אדמת געשית מקומית, לבבות דקל ובשר כשר פרימיום — עם פרטי כשרות שיאושרו בשיחת התאמה.",
        },
        {
          label: "שלב 04",
          title: "שבת של הרמוניה",
          body: "התחברו לעומק בשבת. היכנסו למקום קדוש וללא טלפונים, מוקף בערפל מתגלגל — עם סעודות חגיגיות, הרצאות מעוררות השראה, תפילה יפה וזמירות מסורתיות.",
        },
        {
          label: "שלב 05",
          title: "טיולים מוקפדים",
          body: "גלו טיפוסים פרטיים לפסגות געשיות, מסלולי זipline מותאמים או שייט קטמרן לשקיעה. כל מסלול מכבד את זמני התפילה ואת מגבלות הכשרות.",
        },
      ],
    },
    dining: {
      eyebrow: "מצוינות קולינרית",
      title: "אוכל כשר, ללא פשרות.",
      body: "צוות הקולינריה שלנו מכין תפריטים יומיים החוגגים את שפע קוסטה ריקה. פרטי הכשרות יאושרו בשיחת התאמה, עם אוכל בהובלת שף המותאם לצרכי המשפחה ולעונת השהייה.",
      checklist: [
        {
          title: "סטנדרטי גלאט / מהדרין",
          body: "פרטי הכשרות יאושרו בשיחת התאמה. העדפות מהדרין ניתנות לאירוח כשמתואמות מראש.",
        },
        {
          title: "מהשדה אל השולחן — אדמת געש",
          body: "ירקות, פירות יער, עשבי תיבול וקפה מהרים — מגידולים אורגניים מחוות שכנות.",
        },
      ],
      imageAlt: "אוכל כשר יוקרתי עם ירקות קלו ונוף עמק הרים",
    },
    jewishLife: {
      eyebrow: "כוונה רוחנית",
      title: "בנוי סביב קצב החיים היהודי.",
      subtitle: "אפשרות לתיאום צרכים יהודיים מראש, עם אירוח מותאם שבת לאורך השהייה.",
      cards: [
        {
          title: "תמיכה בחיים יהודיים",
          body: "אפשרות לתיאום צרכים יהודיים מראש — הסדרי תפילה, אירוח שבת ותיאום מחשבה לקבוצה שלכם.",
        },
        {
          title: "חוויית שבת",
          body: "אירוח מותאם שבת בסביבה הררית שקטה — ארוחות קהילתיות, אווירה רגועה ומרחב למנוחה אמיתית בטבע.",
        },
        {
          title: "תורה ולימוד",
          body: "שיעורים, חברותא ומלומדים מבקרים לפי בקשה — מותאם לרמת העניין והשמירה של הקבוצה.",
        },
      ],
      imageAlt: "שולחן שבת בריטריט כשר בהרים",
    },
    family: {
      eyebrow: "לכל הדורות",
      title: "חופשה אמיתית ושקטה גם להורים.",
      heroBadge: "ריטריט משפחתי",
      heroTitle: "חוויה משפחתית יוקרתית ושקטה",
      heroBody: "אירוח פרטי למשפחות וקבוצות — סוויטות מרווחות, פעילויות טבע מלוות ותכנון שמאפשר להורים באמת לנוח.",
      heroImageAlt: "ילדים חוקרים פרפרים במסלול טבע טרופי",
      miniCards: [
        { label: "01 / נוחות", title: "סוויטות משפחה" },
        { label: "02 / טבע", title: "פעילויות מודרכות" },
        { label: "03 / אוכל", title: "ארוחות גמישות" },
        { label: "04 / גילוי", title: "טיולים משפחתיים" },
      ],
    },
    carousel: {
      eyebrow: "קנבס The Sanctuary",
      title: "יוקרה בהישג יד.",
      items: [
        { label: "מים", title: "בריכת עננים אינסוף", alt: "בריכת עננים אינסוף בשקיעה" },
        { label: "מנוחה", title: "סpa אבן געש", alt: "חדר טיפולי סpa מאבן געש" },
        { label: "ערבים מכוכבים", title: "טרקלין Starlight", alt: "בריכת נופש טרופית מוקפת דקלים וגבעות ג'ונגל" },
        { label: "בריאות", title: "מרפסת יוגה לזריחה", alt: "לodge הרים עם נוף לעמקים ירוקים וגבעות טרופיות" },
        { label: "הגעה", title: "שדרת דקלים", alt: "שדרה ירוקה מוקפת דקלים המובילה לווילה עם גג קש" },
        { label: "נופים", title: "מרפסת הרים בערפל", alt: "נוף הרים טרופיים מערפל ממרפסת עם מעקה לבן" },
      ],
    },
    experiences: {
      eyebrow: "הרפתקאות אלפיניות",
      title: "הרפתקה, מותאמת לשומרי מצוות.",
      subtitle: "טיולים פרטיים שמכבדים את הכשרות ואת לוח הזמנים שלכם.",
      cards: [
        { badge: "טיול פסגה פרטי", title: "משלחת ל הר איראסו", alt: "מכתש הר הגעש איראסו" },
        { badge: "טיול מבודד", title: "מפלי מים סודיים", alt: "מפל מים סודי" },
        { badge: "ריגוש", title: "מסלול Zipline ביער", alt: "מסלול zip line ביער הג'ונגל" },
        { badge: "בריחה לים", title: "שייט שקיעה פרטי", alt: "שייט קטמרן בשקיעה" },
      ],
    },
    rooms: {
      eyebrow: "חדרי יוקרה",
      title: "נוחות לזוגות ולקבוצות.",
      body: "כל סוויטה ווילה תוכננו בקפידה עם אפשרות להפרדת מיטות, מתקני מטבח כשר ומערכות תואמות שבת.",
      cta: "גלו את החדרים",
      fromPrice: "זמין לפי בקשה",
      perNight: "",
      selectPlanner: "תכננו את השהייה",
      items: {
        "panorama-villa": {
          name: "וילת Panorama",
          category: "אוסף הווילות",
          description: "יצירת מופת אדריכלית בת 4 חדרי שינה, עם תקרות ארז גבוהות, נוף מרהיב ל הר הגעש, בריכת שחייה פרטית מחוממת ומטבחון כשר מצויד עם כיורים כפולים.",
          features: ["בריכה פרטית מחוממת", "מטבח כשר מצויד", "מרפסה פנורמית", "משרת אישי", "הגדרות מנורות שבת"],
        },
        "cloud-forest-suite": {
          name: "סוויטת Cloud Forest",
          category: "סוויטות",
          description: "מקלט אינטימי ושקט לזוגות, עם טקסטורות אלון ופשתן איכותיות, מקלחת גשם חיצונית פרטית וטרסת גינה רחבה עם נוף לעמק.",
          features: ["טרסת גינה פרטית", "מקלחת גשם חיצונית", "מיטות נפרדות/זוגיות", "בר אסpresso כשר", "מצעים יוקרתיים"],
        },
      },
    },
    programs: {
      eyebrow: "עונות מותאמות",
      title: "לוח שנה של Sanctuary.",
      subtitle: "חבילות עונתיות מיוחדות לאורך השנה היהודית.",
      cards: [
        {
          title: "פסח",
          body: "סeder אולטימטיבי תחת כוכבי הקוואטר. תוכניות קולינריות גלאט כשר לפesach, מחנות ילדים ומלומדים — הכול כלול.",
          cta: "בקשו מחירי פסח",
        },
        {
          title: "סוכות",
          body: "סעדו בסוכה ההררית המרהיבה שלנו עם נוף לעמקים אזמרגד. תפילות יפות, קונסיירז' לulav ואתrog, ופעילויות חול המoed.",
          cta: "הזמינו חבילת סוכות",
        },
        {
          title: "ריטריטים חורפיים",
          body: "תהנו משמש הרים צלולה בחורף הצפוני. שבועות פעילים מותאמים למחנות משפחתיים ולמשלחות zip מרגשות.",
          cta: "למידע נוסף",
        },
      ],
    },
    trust: {
      title: "הפרטים חשובים. אנחנו מתכננים אותם.",
      stats: [
        { value: "100%", label: "תעודת גלאט כשר" },
        { value: "24/7", label: "קונסיירז' ייעודי" },
        { value: "פרטי", label: "הסעות שדה תעופה" },
        { value: "מאובטח", label: "אחוזה וולקנית פרטית" },
      ],
    },
    finalCta: {
      eyebrow: "התחילו את המסע",
      title: "חוו יוקרה מוחלטת.",
      body: "צוות האירוח שלנו מוכן לתאם את ריטריט ההרים המותאם אישית שלכם — עם פרטי כשרות שיאושרו בשיחת התאמה.",
      cta: "תכננו את השהייה",
    },
    footer: {
      brand: "Pura Shalom",
      description: "ריטריט כשר יוקרתי ברמת גלאט, בין הרי קרטגו הבתוליים בקוסטה ריקה.",
      badges: ["גלאט כשר 24/7", "שומר שבת"],
      newsletterLabel: "ניוזלטר VIP",
      emailPlaceholder: "הזינו את האימייל שלכם",
      subscribe: "הרשמה",
      exploreTitle: "גלו",
      exploreLinks: ["ההבטחה", "המיקום", "אוכל כשר", "לינה"],
      inquireTitle: "פנו אלינו",
      inquireLinks: ["חבילה מותאמת", "קונסיירז' AI"],
      location: "קרטגו, קוסטה ריקה",
      copyright: "© 2026 Pura Shalom. כל הזכויות שמורות. ריטריט הרים כשר יוקרתי בקוסטה ריקה.",
    },
    planner: {
      eyebrow: "מתכנן Sanctuary",
      title: "התאימו אישית את הריטריט היוקרתי.",
      subtitle: "הגדירו תאריכים, פרמטרי כשרות, טיולים ותכניות משפחתיות — וקבלו הצעת מחיר בזמן אמת להגשת פנייה לצוות הייעוץ שלנו.",
      steps: {
        guestDetails: "פרטי אורח",
        accommodation: "בחירת לינה",
        kashrut: "כשרות וחיים יהודיים",
        excursions: "טיולים והרפתקאות",
        family: "תכניות משפחתיות",
        special: "בקשות מיוחדות והעדפות תזונה",
      },
      labels: {
        fullName: "שם מלא",
        email: "כתובת אימייל",
        phone: "מספר טלפון",
        season: "עונה / חודש מועדף",
        nights: "מספר לילות",
        adults: "מבוגרים (13+)",
        children: "ילדים (0-12)",
        supervision: "סטандарטי השגחה",
        dailyServices: "שירותים יומיים",
        shabbatDining: "סעודות שבת קהילתיות",
        communalSeats: "הקצאת מקומות:",
        rate: "תעריף",
        perNight: " / לילה",
        perPerson: " / לאדם",
        perDay: " / יום",
        perNightChild: "ללילה / ילד",
        estimatedTotal: "סה״כ משוער",
        subjectReview: "בכפוף לבדיקת יועץ",
        privateTour: "טיול פרטי",
        communal: "קבוצתי",
      },
      placeholders: {
        fullName: "לדוגמה: יonathan כהן",
        email: "example@email.com",
        phone: "+972 50-000-0000",
        season: "דצמבר 2026 / חנוכה",
        specialRequests: "לדוגמה: אנחנו חוגגים יום נישואין כסף. נדרש חלב ישראל בלבד, ונשמח לסיוע בלימוד תורה פרטי לבננו ביום שני בבוקר...",
      },
      accommodationHint: "בחרו את החלל האדריכלי המתאים לקבוצה שלכם. כיורים כפולים, חדרי שינה נפרדים ופרמטרים תואמי שבת — משולבים במלואם.",
      kashrutHint: "תוכנית הקולינריה שלנו 100% גלאט כשר, פת ישראל וחלב ישראל. ניתן לבחור פרמטרי כשרות מתקדמים למטה.",
      minyanLabel: "שריון מקומות בבית הכנסת",
      minyanHint: "שריון מרווח מקומות בבית הכנסת לשחרית, מנחה וערבית. כולל סידורים וחומשים.",
      shabbatHint: "שריון שולחן פרטי בסעודת השבת הקהילתית המרהיבה שלנו, עם גביעי קידוש מכסף וחלות מקולפות.",
      excursionsHint: "התאימו את החופשה עם מסלולי טבע פרטיים או ריצות zipline. כל טיול מתוזמן סביב מניינים ומגבלות כשרות.",
      familyHint: "מחנות גשם מלווים, טרקלין לבני נוער ושירותי childcare — כדי שתוכלו להירגע בשקט מוחלט.",
      specialHint: "ספרו לצוות הייעוץ שלנו על צרכי נגישות, השגחות כשרות מיוחדות, אלרגיות או חגיגות (יום נישואין, בר מצווה, reunion משפחתי).",
      submit: "שלחו פנייה ושריינו מקום",
      estimateTitle: "הערכת מחיר מותאמת",
      nightsAdults: "לילות ×",
      adultsWord: "מבוגרים",
      kidsWord: "ילדים",
      supervisionSurcharge: "תוספת השגחה",
      curatedExcursions: "טיולים מוקפדים",
      familyProgramming: "תכניות משפחתיות",
      inclusionsTitle: "כלול בסטандарт:",
      inclusionsBody: "3 ארוחות gourmet גלאט כשר ביום, הסעה משדה התעופה, גישה מלאה לבית הכנסת, מתקני פנאי (בריכת אינסוף, מרפסת יוגה — ללא שייט קatamaran אלא אם נבחר).",
      pledgeTitle: "התחייבות ההזמנה שלנו",
      pledgeBody: "הגשת הפנייה שומרת על מקומכם בעדיפות. קונסיירז' יוקרתי יצור קשר תוך 24 שעות לסקירת לוח הזמנים, לכיוון בקשות מיוחדות ולסגירת ההזמנה.",
      adultsOption: "מבוגרים",
      childrenOption: "ילדים",
      guestsOption: "אורחים",
      validationAlert: "אנא מלאו שם, אימייל ומספר טלפון כדי לבקש זמינות.",
      kashrutTiers: {
        "glatt-standard": {
          name: "גלאט כשר (CRC / OU)",
          description: "משגיח תמידי מלא, פת ישראל וחלב ישראל.",
        },
        "beit-yosef": {
          name: "סטандарт בית יוסף",
          description: "בשר בית יוסף ספרדי מחמיר תחת השגחה גבוהה.",
        },
        chassidish: {
          name: "שחיטה חסidית / מחמיר במיוחד",
          description: "סטандартי כשרות חסidיים הגבohים ביותר, אימות hashgacha מותאם.",
        },
      },
      activities: {
        volcano: {
          name: "משלחת ל הר איראסו",
          description: "סיור פרטי מguided ב מכתש הפעיל, שדות אפר געשי ופסגות מעורפלות — עם ארוחת צהריים כשרה ארוזה.",
          category: "הרפתקה",
        },
        waterfalls: {
          name: "טיול למפלי הגשם הסודיים",
          description: "גלו מפלים נסתרים בבריכות טורקיז, עם naturalists מקצועיים. מסלולים מותאמים לכושר האורחים.",
          category: "טבע",
        },
        canopy: {
          name: "מסלול Zipline בח canopy",
          description: "עופו בבטחה מעל ח canopy יער העננים. אמצעי בטיחות יוצאי דופן ונוף עמק אזמרגד מלמעלה.",
          category: "אדרנalin",
        },
        "sunset-sail": {
          name: "שייט קטמרן פרטי לשקיעה",
          description: "עלו לסיפon teak נקי של יacht יוקרתי בשקיעה. כולל מנות כשרות גלאט ואפשרות לז pairing יין.",
          category: "פנאי",
        },
      },
      familyServices: {
        "kids-camp": {
          name: "מחנה ילדים ביער הגשם",
          description: "טיולי פרפרים מguided, אמנות בוטנית וחקירת טבע טרופית.",
        },
        nanny: {
          name: "שירות מטפלת פרטית",
          description: "טיפול ילדים יוקרתי מקצועי לפי דרישה.",
        },
        "teen-lounge": {
          name: "גישה לטרקלין בני נוער",
          description: "biljard, ארcade, קונסolות משחק וטיולי hiking מguided לבני נוער.",
        },
      },
    },
    chat: {
      eyebrow: "סיוע בזמן אמת",
      title: "דesk קונסיירז' AI",
      subtitle: "שאלו על כשרות, מניינים, בייבי-sitter, מפלים פרטיים או מזג אוויר הררי.",
      conciergeName: "קונסיירז' The Sanctuary",
      conciergeRole: "יועץ אירוח יוקרתי",
      poweredBy: "מופעל על ידי Gemini",
      loading: "קונסיירז' The Sanctuary מכין הצעות מותאמות...",
      placeholder: "שאלו על כשרות, שבת, חדרים, טיולים ומזג אוויר...",
      welcome: `שלום וברוכים הבאים. אני "קונסיירז' The Sanctuary", יועץ האירוח היוקרתי האישי שלכם.

אני לשירותכם המלא לתיאום פרמטרי גלאט כשר, טיולי געש מותאמים ובקשות רוחניות — כאן בהרי קרטגו היפים והצלולים של קוסטה ריקה.

איך אוכל להתאים אישית את חופשת היוקרה שלכם? שאלו על החדרים, תעודת הכשרות, לוח השבת או טיולי יום.`,
      errorFallback: "מתנצלים, חלה תקלה קלה בחיבור לדesk. הריטריט הכשר שלנו פתוח במלואו — נשמח לסייע דרך טופס הפנייה!",
      emptyResponse: "אני כאן לסייע. ספרו לי במה אוכל לעזור.",
      suggestions: [
        "מהם סטандарטי הכשרות המחמירים שלכם?",
        "ספרו על מתקני וילת Panorama.",
        "איך נראית אווירת השבת ב-Altura?",
        "מה מזג האוויר בהרים בקרטagו?",
        "האם יש טיולים מותאמים ל הר איראסו?",
      ],
    },
    inquiries: {
      eyebrow: "לוח יועץ הנסיעות",
      title: "הפניות החופשה היוקרתיות שלי.",
      subtitle: "עקבו אחר בקשותיכם, הורידו הצעות מחיר, ועקבו אחר הספירה לאחור לחופשה.",
      emptyTitle: "לא נמצאו פניות פעילות",
      emptyBody: "עדיין לא הגשתם פנייה. בקרו במתכנן הריטריט כדי להתאים את החבילה הראשונה שלכם.",
      emptyCta: "פתחו את מתכנן הריטריט",
      submittedLabel: "פניות שהוגשו",
      createNew: "+ צרו תוכנית חדשה",
      statusReview: "בבדיקת יועץ",
      submittedOn: "הוגש ב-",
      countdownLabel: "ספירה לאחור ל-Altura",
      countdownTitle: "מקדש ההרים בקוסטה ריקה ממתין לכם!",
      countdownBody: "יועץ נסיעות כשר יוקרתי יצור קשר עם",
      countdownBodyOr: "או",
      countdownBodyEnd: "בקרוב לקביעת מחיר ותאריכים.",
      daysLabel: "ימים להרפיה",
      specsTitle: "פרטי ההזמנה",
      programmingTitle: "תכניות מוקפדות",
      noActivities: "לא נבחרו טיולים. ניתן לתאם עם היועץ.",
      specialTitle: "בקשות מיוחדות והעדפות",
      costTitle: "הערכת עלות זמנית",
      costSubtitle: "חבילת VIP כוללת",
      costNote: "בכפוף למכפילי עונה מקומיים",
      glattIncluded: "תעודת גלאט כלולה",
      primaryContact: "איש קשר:",
      bespokeDates: "תאריכים:",
      adultGuests: "מבוגרים:",
      kashrutSelection: "רמת כשרות:",
      adultsSuffix: "מבוגרים",
      deleteConfirm: "האם אתם בטוחים שברצונכם לבטל פנייה זו?",
      printTitle: "הדפסת הצעת מחיר",
      deleteTitle: "ביטול/מחיקת פנייה",
      statusPending: "ממתין",
    },
    heroImageAlt: "נוף עמק הררי בריטריט כשר יוקרתי בקרטגו, קוסטה ריקה",
  },
} as const;

export function getSiteContent(language: Language): SiteContent {
  return siteContent[language];
}
